schemes:
  - http
swagger: "2.0"
basePath: /v1
info:
  title: "GCloud photo upload new"
  version: "1.0.0"
paths:
  /photo:
    post:
      consumes:
        - application/json
      description: "Creates new photos"
      operationId: addOrUpdatePhoto
      parameters:
        -
          description: "Photo to be stored"
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Photo"
      produces:
        - application/xml
      responses:
        204:
          description: "OK. Asset tags were updated successfully."
        400:
          description: "Request parameter is not valid."
      summary: "Registering a new photo"
  /photo/search:
    post:
      operationId: getPhotoByFolderAndFileName
      parameters:
          - in: body
            name: status
            required: true
            schema:
              $ref: "#/definitions/PhotoQueryRequest"
      responses:
        200:
          description: "The photo to be returned"
          schema:
            $ref: "#/definitions/PhotoList"



definitions:
  PhotoStatus:
    type: string
    enum: &PHOTOSTATUS
      - synced
      - not_synced
      - failed
  Photo:
    properties:
      fileName:
        type: string
      folderPath:
        type: string
      status:
        default: not_synced
        type: "string"
    type: object
  PhotoList:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/Photo"
  PhotoQueryRequest:
    properties:
      folderPath:
        type: string
      status:
        default: not_synced
        type: "string"
    type: object
